require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'EkoDigital' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/OAuth'

  target 'EkoDigitalTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
  use_unimodules!(exclude: [
    'expo-permissions',
    'unimodules-app-loader',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
    'unimodules-face-detector-interface',
    'unimodules-permissions-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface',
  ])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'EkoDigital-tvOS' do
  # Pods for EkoDigital-tvOS

  target 'EkoDigital-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
